name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run phpcs
        id: phpcs
        continue-on-error: true
        run: ./vendor/bin/phpcs

      - name: Run phpmd
        id: phpmd
        continue-on-error: true
        run: ./vendor/bin/phpmd app text ./phpmd-ruleset.xml

      - name: Run phpstan
        id: phpstan
        continue-on-error: true
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      - name: Check on failures
        if: steps.phpcs.outcome != 'success' || steps.phpmd.outcome != 'success' || steps.phpstan.outcome != 'success'
        run: exit 1
